events {}

http {
    # Define a group of servers for Load Balancing
    upstream api_servers {
        # 'api' is the name of our service in docker-compose.yml
        # Docker's internal DNS will automatically resolve this to all running instances!
        server api:3000;
    }

    server {
        # Nginx listens on port 80 (standard HTTP port)
        listen 80;

        # When a request comes in...
        location / {
            # ... proxy (pass) it to the upstream group we defined above
            proxy_pass http://api_servers;
            
            # Forward important headers to the Node app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
